// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC68U15faR0-YTqKp2eB1PEhZxPp3009yc',
    appId: '1:88721546108:web:f6ea4692e5d9a6cbb7e2f9',
    messagingSenderId: '88721546108',
    projectId: 'flutter-work-with-firebase',
    authDomain: 'flutter-work-with-firebase.firebaseapp.com',
    storageBucket: 'flutter-work-with-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyChCUo9Dc_QOVglzqDxtZAIpfGY4Wm8QBk',
    appId: '1:88721546108:android:d61c815c0152fb66b7e2f9',
    messagingSenderId: '88721546108',
    projectId: 'flutter-work-with-firebase',
    storageBucket: 'flutter-work-with-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDz_8J8Rnsgy0yYkKXGOIJS9J5VH6WARNg',
    appId: '1:88721546108:ios:37b0164b4da541b6b7e2f9',
    messagingSenderId: '88721546108',
    projectId: 'flutter-work-with-firebase',
    storageBucket: 'flutter-work-with-firebase.appspot.com',
    iosClientId: '88721546108-9sg2e2lec2hhbjav6bqasrfquh5tj89t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWorkWithFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDz_8J8Rnsgy0yYkKXGOIJS9J5VH6WARNg',
    appId: '1:88721546108:ios:37b0164b4da541b6b7e2f9',
    messagingSenderId: '88721546108',
    projectId: 'flutter-work-with-firebase',
    storageBucket: 'flutter-work-with-firebase.appspot.com',
    iosClientId: '88721546108-9sg2e2lec2hhbjav6bqasrfquh5tj89t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterWorkWithFirebase',
  );
}
